project:
  type: website
  output-dir: docs

website:
  title: "Kristie's Data Website"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Dashboard
        file: dashboard.qmd
      - text: Shiny Apps
        file: shiny-apps.qmd
      - text: Shinylive
        file: shinylive.qmd
format:
  html:
    theme: cosmo
    toc: true
